### ISSUE TITLE
how can I make a widget multilingual?

### ISSUE THREAD

**Issue by outline4** [carlcs/craft-diywidget#12]
Hi, 

I've created a widget with a text field (cf_welcome_richText) that is translatable within a global variable (gl_text). 

Changing the language in the cp won't change the output language of the text field. 

The widget is as simple as this: 

	<p>
	    {{ "Hello"|t }} {{ currentUser.friendlyName }}!
	</p>
	
	{{ gl_text.cf_welcome_richText }}

The static translation of "Hello" works fine, but the field "cf_welcome_richText" is not translated, although I've translated it under the global vars. 

Is there a way to make the widget multilingual?

**Comment by carlcs** [comment]
Hi, can you try if it works if the text field is in an entry instead of a global?
