### ISSUE TITLE
Feature request : Sprig

### ISSUE THREAD

**Issue by spotd** [carlcs/craft-diywidget#14]
Is there any way to get sprig working in these twig templates?

**Comment by carlcs** [comment]
Hi, I guess you tried to use it and it didn’t work? I have never used Sprig, so can't really help much. Open to review and accept a PR for support though.

**Comment by spotd** [comment]
Ok, yes your right :)

Have tried this but didnt seem to work -> https://putyourlightson.com/plugins/sprig#control-panel-usage

I just need be able to use in frame filters (select form fields) to re-render results etc. I guess form params could work?

**Comment by carlcs** [comment]
Do you have a custom module? Where you could try to add this `Sprig::bootstrap();` call?

**Comment by spotd** [comment]
No i tried with your plugin

**Comment by carlcs** [comment]
Hey Mark, I pushed a release with Sprig support.

I’d appreciate it if you could give feedback, as I don’t have much experience with Sprig. I tested with the basic search example from docs, with Sprig partial uploaded to "config/diy-widget/_sprig-search.twig" and including it from the widget template like so `{{ sprig('diy-widget/_sprig-search') }}`.

**Comment by spotd** [comment]
Brilliant - sounds like it should work. ill test tomorrow as just back from NY

**Comment by spotd** [comment]
Have tested the first 2 from here -> https://putyourlightson.com/sprig/cookbook
they display, but actions dont work (like load another button).

**Comment by carlcs** [comment]
Weird, can you try this example, it worked for me. https://putyourlightson.com/sprig/demo/1

**Comment by spotd** [comment]
i unistalled and re-installed. Get server errors reported when sprig is trying to action

<img width="1294" alt="Screenshot 2024-10-31 at 16 55 10" src="https://github.com/user-attachments/assets/97dcc892-95ca-4fcc-b3cf-073dad9953eb">

**Comment by spotd** [comment]
ok works now - i had in a sub folder and also needs 'diy-widget/' in path

**Comment by spotd** [comment]
Done some more tests, now diy-widget is in include path all works, thanks
