### ISSUE TITLE
Installed via Control Panel. What's next?

### ISSUE THREAD

**Issue by moondawg69** [carlcs/craft-diywidget#3]
As per the title?

**Comment by carlcs** [comment]
Yeah sorry, docs will be updated soon. The repo comes with an examples folder, create a folder config/diy-widget/ in your project and copy everything from _examples/diy-widget/ into it, you should now be able to select and add the widgets to your dashboard.

**Comment by moondawg69** [comment]
Thank you. I am crying with laughter that there is now a weekday bear on my Dashboard ;)

**Comment by evanwarner** [comment]
Aha, key difference from Craft 2 is the config folder being named `diy-widget` instead of `diywidget`. Came here with the same "what do I do?" question and that solved my problem.
