### ISSUE TITLE
Relocate diy-widget

### ISSUE THREAD

**Issue by ben-callaway** [carlcs/craft-diywidget#5]
Can the diy-widget directory be relocated to templates? Seems more appropriate here.

**Comment by carlcs** [comment]
It’s hardcoded to config/diy-widget/, which feels like a good location to me actually. Similar to other plugins that have their “configuration files” in a subfolder of config/, for example, config/element-api/EntryTransformer.php, config/redactor/Simple.json or config/redactor/plugins/custom-plugin.js

Don’t you think templates/ and web/assets/ is kinda reserved for frontend code?

**Comment by ben-callaway** [comment]
It's probably because I don't have any other plugin files in the config it looked a little out of place but makes sense. Nice plugin by the way, lots of use cases!
