### ISSUE TITLE
Breaking in Craft 3.1.25

### ISSUE THREAD

**Issue by shornuk** [carlcs/craft-diywidget#7]
Just updated Craft to 3.1.25 and getting a `There was an error while rendering the widget.` error on all the widgets. Checking logs shows 'unable to find template' error for each widget, but the templates are there and they register as widgets in the 'new widget' dropdown. 

Also, not sure if this is related, but tried installing on a fresh Craft install from the plugin store and get the following `{"error":"No plugin exists with the handle \"diy-widget\"."}`

**Comment by carlcs** [comment]
Tricky one, as I can’t reproduce either of your issues. Widgets continue working just fine on Craft 3.1.25. And I also tried to install the plugin from the store on a fresh install. It took a very long time (I always use Composer directly from the command line), but I eventually got the “All fine” message and the plugin was installed and enabled.

Can you please help to debug and add the following code after line 112 (`$view->setTemplatesPath...`) in the widgets service, which is located at vendor/carlcs/craft-diywidget/src/services/Widgets.php.

```php
Craft::dd($view->getTemplatesPath() . '/' . $templatePath);
```

When you now visit the dashboard you should see the template path the plugin uses to render the widget. The output should hopefully give us a clue why Twig isn’t able to find the template.

**Comment by shornuk** [comment]
Thanks for that. Managed to get a fresh install working. Think clearing my composer cache helped ;)

We've reduced the test case to a single widget  and added the `dd` and the template path is correct. We've done a little more debugging and seems like the exception is being thrown in the twig `render` method. We're on Twig 2.8.1 (which was updated as part of Craft 3.1.24).

**Comment by shornuk** [comment]
OK, a bit more digging and it appears it's the Searchit plugin that's causing a conflict/issue. Will report back once fixed.

**Comment by carlcs** [comment]
It seems like Craft’s “Template Mode“ doesn’t remember the path it was configured to when you’re switching back and forth so you’d have to take care of that yourself (at least when you’re hooking into Twig rendering events. https://github.com/fruitstudios/craft-searchit/blob/master/src/models/ElementFilter.php#L171

**Comment by carlcs** [comment]
@shornuk any updates on this?

**Comment by carlcs** [comment]
@shornuk can we close here? Do you have an issue open over at Searchit repo?

**Comment by shornuk** [comment]
Yea, let's close this one up. We're looking into it on Searchit.
