### ISSUE TITLE
Widgets are not rendered

### ISSUE THREAD

**Issue by Kota-M** [carlcs/craft-diywidget#8]
I have just installed the plugin for our Craft, but my widget is not rendered due to this error; There was an error while rendering the widget. It was the same result even I copied one of the sample widgets.

As you wrote for the previous issue, I tried to insert the line, but it made our Craft not working.

Could you help me to make it works?

By the way, my Craft is 3.1.30.

**Comment by carlcs** [comment]
What other plugins do you have installed? I know there’s a conflict with Searchit that doesn’t seem to be fixed yet.

**Comment by carlcs** [comment]
See #7

**Comment by Kota-M** [comment]
That site has Freeform Lite, Google Maps API, Guest Entries, Redactor, Sprout E-mail, and some other plugins.

I have already seen #7, but that additional code did not help me.

**Comment by carlcs** [comment]
Is Searchit among the other plugins? In your logs do you also have the `unable to find template` error mentioned in the other issue?

> I tried to insert the line, but it made our Craft not working

Did you import the `Craft` class when you edited the file (see [PHP namespaces](https://www.php.net/manual/en/language.namespaces.importing.php))?

**Comment by Kota-M** [comment]
No, the site does not have Searchit plugin. And I cannot find `unable to find template` error in the log file.

And do you mean the part of `Craft::` ? Then yes, I inserted the code with it.
