### ISSUE TITLE
Feature request: custom twig functions

### ISSUE THREAD

**Issue by anchovy** [carlcs/craft-diywidget#9]
Hi

Great plugin - any way out of the box to use/register twig functions?

Thanks in advance.

Regards
Ben

**Comment by carlcs** [comment]
Hi Ben, not sure I understand your question. You should be able to use any Twig function in your Widget template like you do in your frontend templates.

**Comment by carlcs** [comment]
Hi Ben, not sure I understand your question. You should be able to use any Twig function in your Widget template like you do in your frontend templates.

**Comment by anchovy** [comment]
Hi @carlcs 

I was referring to _custom_ twig functions rather than common Twig functions... i.e have a diyWidgetTwigExtension 

```
....
use Twig\Extension\AbstractExtension;
use Twig\TwigFilter;
use Twig\TwigFunction;
class diyWidgetTwigExtension extends AbstractExtension
{

    /**
     * Returns an array of Twig functions, used in Twig templates via:
     *
     *      {% set this = someFunction('something') %}
     *
    * @return array
     */
    public function getFunctions()
    {
        return [
            new TwigFunction('custom_function', [$this, 'customTwigFunction'])
        ];
    }

    public function customTwigFunction()
    {
        return 'foo';
    }
 ........
}
```

So in the widget template you can call these functions (and filters etc)

`{% set result = custom_function() %}`


Regards
Ben

**Comment by carlcs** [comment]
Hm yeah, I don’t see why your custom Twig function shouldn’t work in a widget. Did you actually try it, and it did work in frontend templates?

**Comment by anchovy** [comment]
I was sort of meaning within your plugin - so you'd have, or could have the existing (optional for svg, js, css etc) files:
countdown.html
countdown.svg
countdown.js
countdown.css

And also
_countdownTwigExtensions.php_

The plugin would automagically register twigExtension class and make the functions & filters available in the countdown.html template.

Regards
Ben

**Comment by carlcs** [comment]
Oh, now I get it. I’m not completely convinced that this is common enough to justify having this as a feature of the plugin itself. Can you tell me more about your use case? What are you doing in the widget template where using Twig doesn’t feel right? And is this something that you’d want to re-use in multiple projects?

**Comment by anchovy** [comment]
Sweet - in this case, I'm going to be interacting with commerce orders (and commerce statuses, shipping methods) and craft users. In other cases I'd be wanting to use/interact with freeform & users etc.

Some of this can be done in twig functions, but some can't.... I suppose ideally there would be the possibility to add a controller as well to handle ajax requests... but that might be one feature request to far!

Anyway - just a thought!

**Comment by carlcs** [comment]
Yeah, I won’t make it possible to register custom controllers, but the plugin already provides an action that allows you to render DIY widget templates. It’s being used in the Search example widget [search.js](https://github.com/carlcs/craft-diywidget/blob/8c7b8601084cecc6c4e5b6f50836256383ac7a6c/_examples/src/search.js#L75-L90
).

After giving your original request another thought, I decided to make it possible to register template hooks by uploading PHP files to `config/diy-widget`. It would be nice if you could install the updates and provide feedback before I’m going to tag a new release.

To do that change your requirements in composer.json and run `composer update`.

```
"require": {
  "carlcs/craft-diywidget": "v2.x-dev",
}
```

**Comment by carlcs** [comment]
This is how the PHP file providing the template hook should look like.

template-hook.php
```php
<?php
return function(&$context) {
    $context['hookName'] = 'diy.' . pathinfo(__FILE__, PATHINFO_FILENAME);
};
```

template-hook.twig
```twig
{% hook 'diy.template-hook' %}
<p>{{ hookName }}</p>
```

**Comment by anchovy** [comment]
Wicked @carlcs - I'll take a look.
Could be a good idea to add to the readme/examples to help other users that also want to use custom twig functions.
